// TraceChain Forensic Store & Case Intelligence Generator
import type {
  InvestigationCase,
  Alert,
  WatchlistWallet,
  UserProfile,
  VaspDirectoryEntry,
} from "./types";

export const AVAILABLE_USERS: UserProfile[] = [
  {
    id: "usr-1",
    name: "Inspector Vikram Mehta",
    email: "vikram.mehta@cybercrime.gov.in",
    role: "INVESTIGATOR",
    department: "Cyber Crime Financial Investigation Unit",
    agency: "Delhi Police Cyber Cell / NCRP Desk",
  },
  {
    id: "usr-2",
    name: "Dr. Anya Sharma",
    email: "anya.sharma@forensics.org",
    role: "ANALYST",
    department: "Blockchain Intelligence & Heuristics",
    agency: "National Cyber Forensics Laboratory",
  },
  {
    id: "usr-3",
    name: "Superintendent Rajesh Rao",
    email: "rajesh.rao@police.gov.in",
    role: "ADMIN",
    department: "Directorate of Criminal Investigation",
    agency: "Central Bureau of Investigation (CBI)",
  },
  {
    id: "usr-4",
    name: "Legal Officer Priya Nair",
    email: "priya.nair@prosecution.gov.in",
    role: "VIEWER",
    department: "State Prosecution Audit Cell",
    agency: "Directorate of Enforcement (ED)",
  },
];

export const INITIAL_CASES: InvestigationCase[] = [
  {
    id: "TC-2025-0841",
    title: "Sha Zhu Pan (Pig Butchering) -> OKX Hot Deposit Gateway",
    description: "WhatsApp romance inducement leading to fake liquidity pool. 142,500 USDT funnelled via 2 transit burner wallets directly into OKX hot deposit.",
    reportedWallet: "0x71c0429f939e0807b1d1bc65860d5b77ecb2a601",
    chain: "ethereum",
    status: "VASP_IDENTIFIED",
    riskBand: "CRITICAL",
    riskScore: 94,
    priorityScore: 91,
    typology: "PIG_BUTCHERING",
    reportedLossUsd: 142500,
    traceableUsd: 138200,
    complaintRef: "NCRP-2025-MH-94821",
    complaintText: "Victim was contacted via dating application and convinced to invest savings into a high-yield decentralized arbitrage pool. Initial withdrawal succeeded, following which a major deposit of 142,500 USDT was stolen and swept into mixer/burners.",
    investigator: "Inspector Vikram Mehta",
    recoveryProbability: 0.88,
    extractedWallets: [
      "0x71c0429f939e0807b1d1bc65860d5b77ecb2a601",
      "0x892a019483012984029482049280492840928402",
      "0x6cc5f688a315f3dc28a7781717a9a798a59fda7b",
    ],
    victimName: "Rohan Kapoor",
    victimEmail: "rohan.k@gmail.com",
    assignedTo: "Inspector Vikram Mehta",
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    targetVasp: "OKX Exchange",
    freezeStatus: "SUBMITTED",
    notes: [
      {
        id: "note-1",
        body: "Victim lured through fake dating profile on Tinder, redirected to malicious liquidity staking dApp.",
        text: "Victim lured through fake dating profile on Tinder, redirected to malicious liquidity staking dApp.",
        author: "Inspector Vikram Mehta",
        createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
      {
        id: "note-2",
        body: "Automated heuristic detected 2 burner hops before consolidation into OKX 3 Deposit Address.",
        text: "Automated heuristic detected 2 burner hops before consolidation into OKX 3 Deposit Address.",
        author: "TRACE-AI Heuristic Engine",
        createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
      },
    ],
    activity: [
      {
        id: "act-1",
        action: "CASE_CREATED",
        detail: "FIR NCRP-2025-MH-94821 ingested via National Cyber Crime Reporting Portal",
        actor: "System",
        createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
      },
      {
        id: "act-2",
        action: "VASP_ATTRIBUTION",
        detail: "Attributed final hop to OKX Hot Deposit Wallet (0x6cc5f688a315f3dc28a7781717a9a798a59fda7b) with 98% confidence",
        actor: "TraceChain Engine",
        createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "TC-2025-0792",
    title: "Telegram Work-From-Home Task Scam -> Binance TRC-20 Fan-Out",
    description: "Daily task review fraud targeting victims across Mumbai & Bangalore. TRC-20 USDT multi-sender aggregation routed into Binance deposit address.",
    reportedWallet: "TQ41vQxX9bW9pLz7Y2N1jK6mM4vR8eT3sA",
    chain: "tron",
    status: "ACTION_REQUIRED",
    riskBand: "HIGH",
    riskScore: 86,
    priorityScore: 88,
    typology: "TASK_SCAM",
    reportedLossUsd: 48000,
    traceableUsd: 46500,
    complaintRef: "NCRP-2025-KA-38102",
    complaintText: "Part-time job fraud promising ₹5,000/day for reviewing hotel listings on Google Maps. Victim directed to purchase crypto through OTC P2P desks and transfer TRC-20 USDT to syndicate wallets.",
    investigator: "Dr. Anya Sharma",
    recoveryProbability: 0.74,
    extractedWallets: [
      "TQ41vQxX9bW9pLz7Y2N1jK6mM4vR8eT3sA",
      "TMuA6YqfCeX8EhbfYEg5y7S4D1Dc2M4K8A",
    ],
    victimName: "Sneha Reddy",
    victimEmail: "sneha.reddy@techfirm.in",
    assignedTo: "Dr. Anya Sharma",
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    targetVasp: "Binance Global",
    freezeStatus: "NOT_REQUESTED",
    notes: [
      {
        id: "note-1",
        body: "Victim paid via UPI -> Crypto OTC -> TRC-20 USDT. Total 12 victim payments mapped to this cluster.",
        text: "Victim paid via UPI -> Crypto OTC -> TRC-20 USDT. Total 12 victim payments mapped to this cluster.",
        author: "Dr. Anya Sharma",
        createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
      },
    ],
    activity: [
      {
        id: "act-1",
        action: "CASE_CREATED",
        detail: "Case registered from Cyber Crime Division Karnataka",
        actor: "Dr. Anya Sharma",
        createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "TC-2025-0619",
    title: "Healthcare Ransomware Extortion -> Peel Chain -> Wasabi Mixer",
    description: "LockBit 3.0 extortion against medical diagnostic laboratory. 5.2 BTC ransom peeled through 8 unspent outputs towards coinjoin coordinator.",
    reportedWallet: "bc1qa5wkf603fnqap32s9xuv77926s8543u08zkm5m",
    chain: "bitcoin",
    status: "TRACING",
    riskBand: "CRITICAL",
    riskScore: 98,
    priorityScore: 95,
    typology: "RANSOMWARE",
    reportedLossUsd: 320000,
    traceableUsd: 295000,
    complaintRef: "CBI-BSFB-2025-014",
    complaintText: "Hospital enterprise patient data database encrypted by LockBit 3.0 affiliate demanding 5.2 BTC ransom to unseal patient medical charts and operating theatre schedules.",
    investigator: "Inspector Vikram Mehta",
    recoveryProbability: 0.62,
    extractedWallets: [
      "bc1qa5wkf603fnqap32s9xuv77926s8543u08zkm5m",
      "bc1q9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d",
      "34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo",
    ],
    victimName: "Apex Diagnostics Healthcare Ltd",
    assignedTo: "Inspector Vikram Mehta",
    createdAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    targetVasp: "Wasabi CoinJoin Protocol",
    freezeStatus: "NOT_REQUESTED",
    notes: [
      {
        id: "note-1",
        body: "High-priority ransomware case. 3 peel steps analyzed, 2 BTC still parked in intermediate change wallet.",
        text: "High-priority ransomware case. 3 peel steps analyzed, 2 BTC still parked in intermediate change wallet.",
        author: "Inspector Vikram Mehta",
        createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      },
    ],
    activity: [
      {
        id: "act-1",
        action: "CASE_CREATED",
        detail: "Referred by Central Bureau of Investigation Cyber Forensics",
        actor: "Inspector Vikram Mehta",
        createdAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "TC-2025-0512",
    title: "Phishing Drainer (Permit2 Exploit) -> Stolen ERC-20 Liquidation",
    description: "Fake Revoke.cash phishing email drained victim's wallet containing 15.4 ETH and assets. Traced to Uniswap v3 and Bybit deposit gateway.",
    reportedWallet: "0x12a9382e7193bca8892182937812903829102931",
    chain: "ethereum",
    status: "FREEZE_REVIEW",
    riskBand: "HIGH",
    riskScore: 82,
    priorityScore: 78,
    typology: "PHISHING",
    reportedLossUsd: 58000,
    traceableUsd: 54000,
    complaintRef: "NCRP-2025-DL-11029",
    complaintText: "Victim received fraudulent security advisory claiming approval exploit vulnerabilities on wallet. Signed Permit2 gasless approval which immediately swept wallet tokens.",
    investigator: "Dr. Anya Sharma",
    recoveryProbability: 0.81,
    extractedWallets: [
      "0x12a9382e7193bca8892182937812903829102931",
      "0x28c6c06298d514db089934071355e5743bf21d60",
    ],
    victimName: "Aditya Verma",
    assignedTo: "Dr. Anya Sharma",
    createdAt: new Date(Date.now() - 160 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    targetVasp: "Bybit Global",
    freezeStatus: "SUBMITTED",
    notes: [],
    activity: [
      {
        id: "act-1",
        action: "CASE_CREATED",
        detail: "Case registered from Cyber Crime Cell New Delhi",
        actor: "Dr. Anya Sharma",
        createdAt: new Date(Date.now() - 160 * 3600 * 1000).toISOString(),
        timestamp: new Date(Date.now() - 160 * 3600 * 1000).toISOString(),
      },
    ],
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: "alt-1",
    type: "VASP_DEPOSIT_DETECTED",
    severity: "CRITICAL",
    message: "138,200 USDT consolidated into OKX Hot Wallet deposit gateway. Freeze window: 3h remaining.",
    caseId: "TC-2025-0841",
    walletAddress: "0x71c0429f939e0807b1d1bc65860d5b77ecb2a601",
    chain: "ethereum",
    acknowledged: false,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "alt-2",
    type: "PEEL_CHAIN_MOVEMENT",
    severity: "HIGH",
    message: "New peel transaction detected: 0.85 BTC sliced from ransomware transit address to Wasabi Coordinator.",
    caseId: "TC-2025-0619",
    walletAddress: "bc1qa5wkf603fnqap32s9xuv77926s8543u08zkm5m",
    chain: "bitcoin",
    acknowledged: false,
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
  },
  {
    id: "alt-3",
    type: "HIGH_VELOCITY_FAN_OUT",
    severity: "MEDIUM",
    message: "TRON address TQ41vQxX9bW9pLz7Y2N1jK6mM4vR8eT3sA executed 14 outgoing transfers within 6 minutes.",
    caseId: "TC-2025-0792",
    walletAddress: "TQ41vQxX9bW9pLz7Y2N1jK6mM4vR8eT3sA",
    chain: "tron",
    acknowledged: false,
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
  },
  {
    id: "alt-4",
    type: "NEW_VICTIM_LINKED",
    severity: "LOW",
    message: "National Cyber Crime Reporting Portal matched new complaint to existing fraud cluster #FC-91.",
    caseId: "TC-2025-0841",
    acknowledged: true,
    createdAt: new Date(Date.now() - 600 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_WATCHLIST: WatchlistWallet[] = [
  {
    id: "watch-1",
    address: "0x71c0429f939e0807b1d1bc65860d5b77ecb2a601",
    chain: "ethereum",
    label: "Pig Butchering Transit Burner",
    riskBand: "CRITICAL",
    riskScore: 94,
    status: "ALERTING",
    caseId: "TC-2025-0841",
    lastActive: "2 hours ago",
    balance: 0.042,
    balanceUsd: 142000,
    ticker: "ETH",
    lastCheckedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    notes: "Direct recipient from victim. Offramping to OKX.",
  },
  {
    id: "watch-2",
    address: "TQ41vQxX9bW9pLz7Y2N1jK6mM4vR8eT3sA",
    chain: "tron",
    label: "Task Scam TRC-20 Hub",
    riskBand: "HIGH",
    riskScore: 86,
    status: "ACTIVE",
    caseId: "TC-2025-0792",
    lastActive: "5 hours ago",
    balance: 1420.5,
    balanceUsd: 48000,
    ticker: "TRX",
    lastCheckedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    notes: "Aggregator for telegram task fraud.",
  },
  {
    id: "watch-3",
    address: "bc1qa5wkf603fnqap32s9xuv77926s8543u08zkm5m",
    chain: "bitcoin",
    label: "LockBit 3.0 Ransomware Primary",
    riskBand: "CRITICAL",
    riskScore: 98,
    status: "MONITORING",
    caseId: "TC-2025-0619",
    lastActive: "1 hour ago",
    balance: 2.14,
    balanceUsd: 210000,
    ticker: "BTC",
    lastCheckedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    notes: "Peel chain origin wallet.",
  },
];

export const SAMPLE_VASPS: VaspDirectoryEntry[] = [
  {
    id: "vasp-binance",
    name: "Binance Global",
    legalEntity: "Binance Holdings Ltd.",
    jurisdiction: "Multiple / Cayman / UAE",
    complianceRating: "A (Verified FIU Registered)",
    kycStandard: "Mandatory Level 3 (Govt ID + Biometrics)",
    responseLatencyHours: 4,
    registeredFiu: true,
    contactEmail: "compliance-le@binance.com",
    subpoenaFormat: "Kodak Law Enforcement Portal (LEP)",
    kycLevel: "TIER_3",
    cooperationLevel: "HIGH",
    subpoenaPortal: "https://www.binance.com/en/support/law-enforcement",
    complianceEmail: "compliance-le@binance.com",
    avgFreezeTimeHours: 4,
    categories: ["Centralized Exchange", "Spot / Futures", "P2P Desk"],
  },
  {
    id: "vasp-okx",
    name: "OKX Global",
    legalEntity: "Aux Cayes FinTech Co. Ltd.",
    jurisdiction: "Seychelles / Bahamas / EU Desk",
    complianceRating: "A- (High Cooperation)",
    kycStandard: "Mandatory Level 3 (Facial Recognition)",
    responseLatencyHours: 6,
    registeredFiu: true,
    contactEmail: "lawenforcement@okx.com",
    subpoenaFormat: "OKX Law Enforcement Subpoena System",
    kycLevel: "TIER_3",
    cooperationLevel: "HIGH",
    subpoenaPortal: "https://www.okx.com/help/law-enforcement",
    complianceEmail: "lawenforcement@okx.com",
    avgFreezeTimeHours: 6,
    categories: ["Centralized Exchange", "Web3 Gateway"],
  },
  {
    id: "vasp-bybit",
    name: "Bybit Fintech",
    legalEntity: "Bybit Fintech Limited",
    jurisdiction: "Dubai (VARA Regulated)",
    complianceRating: "B+ (Responsive to Court Orders)",
    kycStandard: "Level 2 (National Identity)",
    responseLatencyHours: 8,
    registeredFiu: false,
    contactEmail: "compliance@bybit.com",
    subpoenaFormat: "Bybit LE Portal Direct Filing",
    kycLevel: "TIER_2",
    cooperationLevel: "HIGH",
    subpoenaPortal: "https://www.bybit.com/en/support/le-inquiry",
    complianceEmail: "compliance@bybit.com",
    avgFreezeTimeHours: 8,
    categories: ["Centralized Exchange", "Derivatives"],
  },
  {
    id: "vasp-kucoin",
    name: "KuCoin",
    legalEntity: "Meku Global Limited",
    jurisdiction: "Seychelles",
    complianceRating: "B (Requires Formal MLAT / Letters Rogatory)",
    kycStandard: "Level 2 (ID Document)",
    responseLatencyHours: 18,
    registeredFiu: false,
    contactEmail: "compliance@kucoin.com",
    subpoenaFormat: "Formal Embassy/Court Injunction",
    kycLevel: "TIER_2",
    cooperationLevel: "MEDIUM",
    subpoenaPortal: "https://www.kucoin.com/support",
    complianceEmail: "compliance@kucoin.com",
    avgFreezeTimeHours: 18,
    categories: ["Centralized Exchange"],
  },
  {
    id: "vasp-wasabi",
    name: "Wasabi CoinJoin / zkSNACKs",
    legalEntity: "Decentralized / Non-Custodial",
    jurisdiction: "Decentralized (No Subpoena Liaison)",
    complianceRating: "F (Non-Custodial Privacy Protocol)",
    kycStandard: "Anonymous (Zero KYC)",
    responseLatencyHours: 0,
    registeredFiu: false,
    contactEmail: "N/A",
    subpoenaFormat: "N/A (Smart Contract / P2P Coordinator)",
    kycLevel: "ANONYMOUS",
    cooperationLevel: "NON_COOPERATIVE",
    subpoenaPortal: "N/A (Protocol Level)",
    complianceEmail: "N/A",
    avgFreezeTimeHours: 0,
    categories: ["Privacy Mixer", "UTXO CoinJoin"],
  },
];

// Generates complete graph, journey, VASP attribution, patterns, and evidence for any case
export function generateCaseInvestigationData(c: InvestigationCase) {
  const asset = c.chain === "bitcoin" ? "BTC" : c.chain === "tron" ? "TRX" : "ETH";
  const reportedLoss = c.reportedLossUsd || 100000;
  const traceable = c.traceableUsd || 95000;
  const victimAddr = "0x4a8b1c09930e012398452109823019842109384a";
  const suspectAddr = c.reportedWallet;
  const hop1Addr =
    c.chain === "bitcoin"
      ? "bc1q9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d"
      : "0x892a019483012984029482049280492840928402";
  const hop2Addr =
    c.chain === "bitcoin"
      ? "bc1q7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a"
      : "0x3849102938401928409182304918203948102938";
  const targetVaspAddr =
    c.chain === "bitcoin"
      ? "34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo"
      : "0x28c6c06298d514db089934071355e5743bf21d60";

  const nodes = [
    {
      id: "node-victim",
      label: "Victim Wallet",
      kind: "VICTIM" as const,
      address: victimAddr,
      riskScore: 5,
      isVictim: true,
      isVasp: false,
      balance: 0.1,
      usdValue: 240,
    },
    {
      id: "node-suspect",
      label: "Suspect Primary",
      kind: "SUSPICIOUS" as const,
      address: suspectAddr,
      riskScore: c.riskScore,
      isVictim: false,
      isVasp: false,
      balance: 1.45,
      usdValue: reportedLoss * 0.15,
    },
    {
      id: "node-hop1",
      label: "Transit Burner Hop 1",
      kind: "BURNER" as const,
      address: hop1Addr,
      riskScore: 88,
      isVictim: false,
      isVasp: false,
      balance: 0.05,
      usdValue: 120,
    },
    {
      id: "node-hop2",
      label: "Consolidation Burner Hop 2",
      kind: "BURNER" as const,
      address: hop2Addr,
      riskScore: 92,
      isVictim: false,
      isVasp: false,
      balance: 0.02,
      usdValue: 50,
    },
    {
      id: "node-vasp",
      label: c.targetVasp || "Attributed VASP Deposit Gateway",
      kind: "VASP" as const,
      address: targetVaspAddr,
      riskScore: 95,
      isVictim: false,
      isVasp: true,
      balance: 420.5,
      usdValue: traceable,
    },
  ];

  const edges = [
    {
      id: "edge-1",
      txHash: "0xfa71928340192840918230948102938401928340192834019283401928340192",
      source: victimAddr,
      target: suspectAddr,
      kind: "DIRECT_INDUCEMENT",
      amount: reportedLoss / 2400,
      asset,
      usdValue: reportedLoss,
      timestamp: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    },
    {
      id: "edge-2",
      txHash: "0x9182309481029384019283401928340192834019283401928340192834019283",
      source: suspectAddr,
      target: hop1Addr,
      kind: "OBFUSCATION_PEEL",
      amount: (traceable * 0.98) / 2400,
      asset,
      usdValue: traceable * 0.98,
      timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    },
    {
      id: "edge-3",
      txHash: "0x1928340192834019283401928340192834019283401928340192834019283401",
      source: hop1Addr,
      target: hop2Addr,
      kind: "RAPID_CONSOLIDATION",
      amount: (traceable * 0.95) / 2400,
      asset,
      usdValue: traceable * 0.95,
      timestamp: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    },
    {
      id: "edge-4",
      txHash: "0x8340192834019283401928340192834019283401928340192834019283401928",
      source: hop2Addr,
      target: targetVaspAddr,
      kind: "EXCHANGE_HOT_DEPOSIT",
      amount: traceable / 2400,
      asset,
      usdValue: traceable,
      timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    },
  ];

  const journey = [
    {
      step: 1,
      title: "Initial Victim Fraud Transfer",
      description: `Victim transferred funds to suspect address ${suspectAddr.slice(0, 10)}... upon social engineering inducement.`,
      timestamp: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
      stage: "INITIAL_THEFT",
      address: suspectAddr,
      txHash: edges[0].txHash,
    },
    {
      step: 2,
      title: "First Obfuscation Transit Hop",
      description: `Funds moved within 45 minutes to transit burner ${hop1Addr.slice(0, 10)}... to evade immediate blacklist filters.`,
      timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      stage: "OBFUSCATION",
      address: hop1Addr,
      txHash: edges[1].txHash,
    },
    {
      step: 3,
      title: "Secondary Multi-Sender Aggregation",
      description: `Aggregated with outputs from 3 other suspect fraud complaints into intermediate wallet ${hop2Addr.slice(0, 10)}...`,
      timestamp: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
      stage: "CONSOLIDATION",
      address: hop2Addr,
      txHash: edges[2].txHash,
    },
    {
      step: 4,
      title: "Direct Hot Deposit into Regulated VASP",
      description: `Target deposited directly into verified ${c.targetVasp || "VASP Exchange"} deposit cluster. KYC freeze action pack prepared.`,
      timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      stage: "VASP_DEPOSIT",
      address: targetVaspAddr,
      txHash: edges[3].txHash,
    },
  ];

  const vaspAttribution = {
    vasp: {
      name: c.targetVasp || "Binance Global",
      jurisdiction: "Cayman Islands / UAE / EU Regional Desks",
      kycLevel: "Strict Tier-3 (National ID + Facial Biometrics)",
      cooperationLevel: "High (Subpoena Response SLA < 12 Hours)",
      contactEmail: "compliance-le@binance.com",
    },
    depositAddress: targetVaspAddr,
    recommendedAction:
      "File emergency Section 91/102 CrPC preservation order with target VASP Legal Desk. Request account freeze, KYC dossiers, and IP access audit logs.",
    confidenceScore: 98,
  };

  const patterns = [
    {
      id: "pat-1",
      name: "Peel Chain Obfuscation",
      typology: "UTXO / ERC20 Peel Decomposition",
      severity: "CRITICAL" as const,
      description:
        "High asymmetry outputs detected where small fee-like amounts are split off while primary stolen capital advances toward cashout gateway.",
      confidence: 0.94,
      evidenceTxHashes: [edges[1].txHash, edges[2].txHash],
    },
    {
      id: "pat-2",
      name: "Rapid Fan-Out & Re-Aggregation",
      typology: "Velocity-Based Layering",
      severity: "HIGH" as const,
      description:
        "Transaction intervals between hops were under 40 minutes, strongly characteristic of automated laundering scripts rather than organic retail usage.",
      confidence: 0.89,
      evidenceTxHashes: [edges[2].txHash, edges[3].txHash],
    },
    {
      id: "pat-3",
      name: "Known VASP Hot Wallet Ingress",
      typology: "Off-Ramp Liquidation",
      severity: "CRITICAL" as const,
      description:
        "Final hop verified through on-chain address clustering to match official exchange hot deposit sweep architecture.",
      confidence: 0.98,
      evidenceTxHashes: [edges[3].txHash],
    },
  ];

  const evidence = [
    {
      id: "ev-1",
      title: "On-Chain Raw Transaction Receipts & Merkle Proofs",
      type: "BLOCKCHAIN_LOGS",
      contentHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      algorithm: "SHA-256" as const,
      timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      actor: "TraceChain Autonomous Validator",
      metadata: { txCount: edges.length, network: c.chain, confirmedBlocks: 184 },
    },
    {
      id: "ev-2",
      title: "National Cyber Crime Reporting FIR Evidence Package",
      type: "POLICE_COMPLAINT",
      contentHash: "8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4",
      algorithm: "SHA-256" as const,
      timestamp: c.createdAt,
      actor: c.investigator || "Cyber Cell",
      metadata: { firNumber: c.complaintRef, complainant: c.victimName || "Confidential" },
    },
    {
      id: "ev-3",
      title: "VASP Subpoena Formal Dossier & Section 91 Notice",
      type: "STATUTORY_NOTICE",
      contentHash: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
      algorithm: "SHA-256" as const,
      timestamp: new Date().toISOString(),
      actor: "Lead Investigator",
      metadata: { targetEntity: vaspAttribution.vasp.name, status: "READY_FOR_DISPATCH" },
    },
  ];

  return {
    graph: { nodes, edges },
    journey,
    vaspAttribution,
    patterns,
    evidence,
  };
}
